version: "2.0"

services:
  web:
    build: .
    env_file: 
      - .env
    tty: true
    stdin_open: true
    environment:
      PORT: 3000
      FLASK_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
